// LOGIN -
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// REGISTER -
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// LOAD USER -
export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

// LOGOUT USER -
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

// STUDENT  FYP REGISTRARION -
export const REGISTER_STUDENT_FYP_REQUEST = "REGISTER_STUDENT_FYP_REQUEST";
export const REGISTER_STUDENT_FYP_SUCCESS =  "REGISTER_STUDENT_FYP_SUCCESS";
export const REGISTER_STUDENT_FYP_FAIL =  "REGISTER_STUDENT_FYP_FAIL";

// STUDENT FYP 1 -
export const STUDENT_FYP_1_REQUEST = "STUDENT_FYP_1_REQUEST";
export const STUDENT_FYP_1_SUCCESS = "STUDENT_FYP_1_SUCCESS";
export const STUDENT_FYP_1_FAIL = "STUDENT_FYP_1_FAIL";

// STUDENT FYP 2 -
export const STUDENT_FYP_2_REQUEST = "STUDENT_FYP_2_REQUEST";
export const STUDENT_FYP_2_SUCCESS = "STUDENT_FYP_2_SUCCESS";
export const STUDENT_FYP_2_FAIL = "STUDENT_FYP_2_FAIL";


// STUDENT FYP 3 -
export const STUDENT_FYP_3_REQUEST = "STUDENT_FYP_3_REQUEST";
export const STUDENT_FYP_3_SUCCESS = "STUDENT_FYP_3_SUCCESS";
export const STUDENT_FYP_3_FAIL = "STUDENT_FYP_3_FAIL";

// FORGOT PASSWORD -
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

// RESET PASSWORD -
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";


// COORDINATOR -

// COORDINATOR REGISTER SUPERVISOR -
export const COORDINATOR_REGISTER_SUPERVISOR_REQUEST="COORDINATOR_REGISTER_SUPERVISOR_REQUEST";
export const COORDINATOR_REGISTER_SUPERVISOR_SUCCESS="COORDINATOR_REGISTER_SUPERVISOR_SUCCESS";
export const COORDINATOR_REGISTER_SUPERVISOR_FAIL="COORDINATOR_REGISTER_SUPERVISOR_FAIL";


// COORDINATOR CREATE ANNOUNCEMENT - 
export const COORDINATOR_CREATE_ANNOUNCEMENT_REQUEST ="COORDINATOR_CREATE_ANNOUNCEMENT_REQUEST";
export const COORDINATOR_CREATE_ANNOUNCEMENT_SUCCESS ="COORDINATOR_CREATE_ANNOUNCEMENT_SUCCESS";
export const COORDINATOR_CREATE_ANNOUNCEMENT_FAIL ="COORDINATOR_CREATE_ANNOUNCEMENT_FAIL";

// GET ALL SUPERVISORS FOR THE COORDINATOR -
export const STUDENT_SUPERVISORS_REQUEST = "STUDENT_SUPERVISORS_REQUEST";
export const STUDENT_SUPERVISORS_SUCCESS = "STUDENT_SUPERVISORS_SUCCESS";
export const STUDENT_SUPERVISORS_FAIL = "STUDENT_SUPERVISORS_FAIL";

// GET ALL THE STUDENTS FOR THE COORDINATOR -
export const COORDINATOR_STUDENTS_REQUEST = "COORDINATOR_STUDENTS_REQUEST";
export const COORDINATOR_STUDENTS_SUCCESS = "COORDINATOR_STUDENTS_SUCCESS";
export const COORDINATOR_STUDENTS_FAIL = "COORDINATOR_STUDENTS_FAIL";
 

// DISPLAY STUDENTS FYP REGISTRATION REQUESTS TO SUPERVISORS -
export const SUPERVISOR_FYP_PROPOSAL_REQUEST = "SUPERVISOR_FYP_PROPOSAL_REQUEST";
export const SUPERVISOR_FYP_PROPOSAL_SUCCESS = "SUPERVISOR_FYP_PROPOSAL_SUCCESS";
export const SUPERVISOR_FYP_PROPOSAL_FAIL = " SUPERVISOR_FYP_PROPOSAL_FAIL";

// SUPERVISOR REQUESTS -
export const SUPERVISOR_PROPOSAL_REQUEST = "SUPERVISOR_PROPOSAL_REQUEST";
export const SUPERVISOR_PROPOSAL_SUCCESS = "SUPERVISOR_PROPOSAL_SUCCESS";
export const SUPERVISOR_PROPOSAL_FAIL = " SUPERVISOR_PROPOSAL_FAIL";


// CLEAR ERRORS -
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// CLEAR MESSAGES -
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";